export const GET_CONTACT = "GET_CONTACT";
export const CLEAR_CARD = "CLEAR_CARD";
export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENT_FAILED = "ADD_COMMENT_FAILED"
export const NEW_COMMENT_TEXT = "NEW_COMMENT_TEXT"
export const EDIT_CARD = "EDIT_CARD"
export const UPDATE_CARD = "UPDATE_CARD"
export const DELETE_CONTACT = "DELETE_CONTACT"
